export const endpoints = {
   REGISTER_AGENT: "auth/registerAgent",
   LOGIN_AGENT: "auth/loginAgent",
   GET_COUNTRIES: "country/getCountries",
   GET_AGENT_DETAILS_BY_ID: "/agent/getAgentDetailsById",
   AIRPORT_GET: "/airport/getAirPort",
   GET_FLIGHT_LIST: "agent/flight/getFlightList",
   GET_AIRPORT:"/airport/getAirPort",
   AIRLINE_GET:"/airline/getairline",
   GET_CONTENT_BY_PAGE_NAMES:"content/getContentByPageNames",
   GET_AGENT_CHANGE_REQUEST_CHARGES: "agent/getAgentsChangeRequestCharges",
   AVALIABLE_PNR_AIRPORT_CODE:"/agent/flight/getAvaliablePnrAirportcode",
   GET_TWO_MONTHS_AVALIABLE_PNR:"/agent/flight/getTwoMonthsofAvailablePNR",
   AGENT_FLIGHT_BOOKING_REQUEST:"/agent/booking/flighBookingRequest",
   GET_AGENT_BOOKING_FLIGHT_LIST:"agent/booking/getFlightBookingListOfAgent",
   GET_AGENT_ACCOUNT_STATEMENT:"/agent/account/getAccountStatementOfAgent",
   GET_BANKINFO_LIST:"bank/getBankInfoList",
   AGET_CREATE_DEPOSITE:"/agent/deposit/createDeposit",
   AGENT_GET_DEPOSITE:"/agent/deposit/getDeposit",
   GENERATE_PHONEPE_URL:"/agent/payment/generatePhonePeUrl",
   CHECK_PAYMENT_STATUS: "/agent/payment/checkPaymentStatus",
   CONFIRM_BOOKING_PAYMENT: "agent/booking/confirmBookingPaymentStatus",
   GET_AGENT_ACCOUNT_STATEMENT_BY_DATE:"/agent/account/getAgentAccountStatementByDate",
   AGENT_GET_DEPOSITE_SEARCH:"/agent/deposit/getDepositSearch",
   AGENT_NAME_CHANGE_REGUEST:"/agent/nameChangeRequest/agentNameChangeRequest",
   AGENT_BOOKING_CANCEL_REQUEST:"/agent/booking/requestCancelBooking_Flight",
   GET_PENDING_CANCEL_REQUEST:"/agent/booking/getPendingCancelRequests",
   GET_AGENT_PAYMENT_CREDENTIAL:"/agent/payment/getPaymentCredential",
   GET_AGENT_PAYMENT_MODULE:"/agent/payment/getPaymentModules",
   UPDATE_AGENT_DETAILS:"/agent/updateAgentdetails",
   AGENT_CREATE_CASHDREE_PAYMENT_GATEWAY:"/agent/cashFreePayment/createGateway",
   AGENT_CREATE_ATOM_PAYMENT_GATEWAY:"/agent/atomPayment/createPaymentIntent",
   UPDATE_AGENT_PASSWORD:"/agent/changeAgentPassword",
   GET_STATES_BY_COUNTRY_ID:"states/getStatesbyCountryId",
   AUTH_AGENT_FORGOT_PASSWORD_SEND_OTP:"auth/forgotPasswordSendOtpAgent",
   AUTH_AGENT_FORGOT_PASSWORD_OTP_VERIFY:"auth/forgotPasswordOtpVerifyAgent",
   AUTH_AGENT_FORGOT_PASSWORD:"auth/forgotPasswordAgent",
   AUTH_AGENT_AIR_IQ_FLIGHT_BOOKING:"/agent/booking/air_iq_flight_booking",
   GET_SLIDER_IMAGE:"/sliderImage/getSliderImage",
   UPLOAD_DOCUMENT:"/upload/uploadDocument",


} as const;
